image: ubuntu:focal

stages:
  - build
  - test

before_script:
  - apt-get update -qq && DEBIAN_FRONTEND=noninteractive apt-get install -y git g++ cmake libeigen3-dev rapidjson-dev openssh-client
  - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/Hs293Go/slts_control_sim.git".insteadOf git@gitlab.com:Hs293Go/slts_control_sim.git

variables:
  GIT_SUBMODULE_STRATEGY: none

build:
  stage: build
  script:
    - git submodule update --init --recursive
    - cmake -B build -S .
    - cmake --build build --config Release --target all
  artifacts:
    paths:
      - build/librobust_tracker.a

RunGTest:
  stage: test
  script:
    - git submodule update --init --recursive
    - cmake -B build -S .
    - cmake --build build --config Release --target test_controller
    - build/tests/test_controller

RunCTest:
  stage: test
  script:
    - git submodule update --init --recursive
    - cmake -B build -S .
    - cmake --build build --config Release --target test_controller
    - ctest -j4 -C Release -T test --output-on-failure --test-dir build
