clearvars; close all; clc;
addpath('models', 'utils');
model = 'test_controller';
in = Simulink.SimulationInput(model);
in = in.setModelParameter('SimulationMode', 'accelerator');
in = in.setModelParameter('StopTime', '30');
in = in.setModelParameter('SolverType', 'Fixed-step');
in = in.setModelParameter('FixedStep', '0.01');
in = in.setModelParameter('SolverName', 'euler');

soln = sim(in);

pld = DatasetToStruct(soln, [ ...
                            "pld_abs_pos", ...
                            "pld_rel_pos", ...
                            "pld_abs_vel", ...
                            "pld_rel_vel", ...
                            "act_force", ...
                            "pld_pos_err", ...
                            "pld_vel_err", ...
                            "pld_vel_sp",...
                            "proj_de", ...
                            "total_de", ...
                            "proj_de_est_err", ...
                            "total_de_est_err", ...
                            "pld_swing_est_err"
                        ]);

fid = fopen('test_controller.json', 'w');
fprintf(fid, '%s', jsonencode(pld));
fclose(fid);
