name: test-slts-control

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt-get install libgtest-dev libeigen3-dev ninja-build rapidjson-dev
      - uses: actions/checkout@v1
      - name: configure
        run: cmake -S . -B build -DBUILD_TESTING=ON -GNinja
      - name: make
        run: cmake --build build --config Release --target test_controller
      - name: Run CTest
        run: cd build && ctest -j4 -C Debug -T test --output-on-failure
